name: Node.js CI

on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get current date
        id: currentDate
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Install dependencies
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        run: yarn

      - name: Test
        uses: mujo-code/puppeteer-headful@master
        id: runTest
        env:
          CI: 'true'
        with:
          args: yarn test:ci

      - name: Send telegram with photo message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          photo: github-repo.jpeg
          message: |
            [${{ steps.runTest.conclusion }}] Regular testing (${{ steps.currentDate.outputs.date }})

            See details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Send telegram failure message
        uses: appleboy/telegram-action@master
        if: failure()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            [${{ steps.runTest.conclusion }}] Regular testing (${{ steps.currentDate.outputs.date }})

            See details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Send line with photo message
        uses: louis70109/line-notify-action@master
        with:
          token: ${{ secrets.LINE_NOTIFY_TOKEN }}
          image_file: github-repo.jpeg
          message: |
            [${{ steps.runTest.conclusion }}] Regular testing (${{ steps.currentDate.outputs.date }})

            See details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  
      - name: Send line failure message
        uses: louis70109/line-notify-action@master
        if: failure()
        with:
          token: ${{ secrets.LINE_NOTIFY_TOKEN }}
          message: |
            [${{ steps.runTest.conclusion }}] Regular testing (${{ steps.currentDate.outputs.date }})

            See details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
